### PR TITLE
fix attribute selector

### LINKED ISSUE #69: missing square brackets around import-dependency
https://github.com/webcomponents/html-imports/blob/2fdce2cb070c1c08664aed704b187d0854092c06/src/html-imports.js#L190

I think the intent is to produce this selector: `link[rel=import]:not([import-dependency])`, but it produces `link[rel=import]:not(import-dependency)` which does **not** ignore those imports marked with `import-dependency`.

### PR DESCRIPTION
**Pull request by valdrinkoshi**
Fixes #69 
`rootImportSelector` is used to query all the imports we should wait for. It has a bug on the selector which causes the implementation to wait the loading also for imports that are dependencies of document imports. This doesn't cause stalling, as all imports will fire the load/error event, but is indeed a bug because `link[rel=import]:not(import-dependency)` is not the intended selector.
With this change, we basically speed up the for-loop in `whenImportsReady`.

### CODE REVIEW

**Review by dfreedm — CHANGES_REQUESTED** [review]
LGTM if you add a test!

**Comment by valdrinkoshi** [comment]
@azakus I don't think we can write a test for this change. I've updated the description of the PR with more details ^

**Comment by dfreedm** [comment]
Ah I see. Let's merge it then!

**Review by dfreedm — APPROVED** [review]

**Comment by dfreedm** [comment]
Published as 1.0.2

**Pull request merged**
